AWSTemplateFormatVersion: '2010-09-09'
Description: Open Meteo Weather - Lambda API to CSV Infrastructure

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, qa, staging, prod]
    Default: prod
  LambdaFunctionName:
    Type: String
    Default: api-to-csv-function

Resources:

  # ─────────────────────────────────
  # 1. S3 Bucket
  # ─────────────────────────────────
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "api-to-csv-output-${Environment}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: beastleohfslilly
        - Key: Project
          Value: open-meteo-weather
        - Key: CostCenter
          Value: engineering

  # ─────────────────────────────────
  # 2. IAM Role
  # ─────────────────────────────────
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${OutputBucket}/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: beastleohfslilly
        - Key: Project
          Value: open-meteo-weather
        - Key: CostCenter
          Value: engineering
PandasLayer:
 Type: AWS::Lambda::LayerVersion
 Properties:
  LayerName: pandas-layer
  Description: Pandas dependency layer
  Content:
    S3Bucket: open-meteo-weather-sys-bk
    S3Key: package-lambda-code/pandas_layer.zip
  CompatibleRuntimes:
    - python3.11
  # ─────────────────────────────────
  # 3. Lambda Function  ← WAS MISSING
  # ─────────────────────────────────
  LambdaFunction:
  Type: AWS::Lambda::Function
  Properties:
    FunctionName: !Ref LambdaFunctionName
    Runtime: python3.11
    Handler: app_api_extractor.lambda_handler
    Role: !GetAtt LambdaExecutionRole.Arn
    Timeout: 300
    MemorySize: 512

    Layers:
      - !Ref PandasLayer

    Environment:
      Variables:
        BUCKET_NAME: !Ref OutputBucket
        ENVIRONMENT: !Ref Environment

    Code:
      S3Bucket: !Ref OutputBucket
      S3Key: placeholder.zip

    Tags:
      - Key: Environment
        Value: !Ref Environment
      - Key: Owner
        Value: beastleohfslilly
      - Key: Project
        Value: open-meteo-weather
      - Key: CostCenter
        Value: engineering

  # ─────────────────────────────────
  # 4. CloudWatch Log Group
  # ─────────────────────────────────
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunctionName}"
      RetentionInDays: 30
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: beastleohfslilly
        - Key: Project
          Value: open-meteo-weather
        - Key: CostCenter
          Value: engineering

# ─────────────────────────────────
# Outputs  ← WAS MISSING (caused None error)
# ─────────────────────────────────
Outputs:
  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref LambdaFunction
    Export:
      Name: !Sub "${AWS::StackName}-LambdaName"

  BucketName:
    Description: S3 Output Bucket Name
    Value: !Ref OutputBucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"